"""
Backend Logic for Sabaza Optimizer
Handles translation and Word document generation
"""

from io import BytesIO
from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from deep_translator import GoogleTranslator


def process_report(client_name, notes, should_translate):
    """
    Processes inspection notes and generates a court-ready Word document.

    Args:
        client_name (str): The name of the client/property
        notes (str): The inspection notes (original language)
        should_translate (bool): Whether to translate to Arabic

    Returns:
        BytesIO: A buffer containing the generated Word document

    Raises:
        ValueError: If translation fails or document creation encounters an error
    """

    # Step 1: Translate notes if requested
    final_notes = notes
    if should_translate and notes.strip():
        try:
            # Translating from auto-detect to Arabic
            translator = GoogleTranslator(source='auto', target='ar')
            final_notes = translator.translate(notes)
        except Exception as e:
            # If translation fails, keep original text and append error
            final_notes = f"{notes}\n\n[Translation Error: {str(e)}]"

    # Step 2: Create a new Word Document
    doc = Document()

    # Step 3: Add Title
    title = doc.add_heading(f'Inspection Report: {client_name}', level=1)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    if title.runs:
        title_run = title.runs[0]
        title_run.font.color.rgb = RGBColor(31, 78, 121)  # Professional blue

    # Step 4: Add Findings Heading
    findings_heading = doc.add_heading('Findings', level=2)
    if findings_heading.runs:
        findings_run = findings_heading.runs[0]
        findings_run.font.color.rgb = RGBColor(31, 78, 121)

    # Step 5: Add the inspection notes
    notes_paragraph = doc.add_paragraph(final_notes)
    # If Arabic, align Right. If not, align Left.
    if should_translate:
        notes_paragraph.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    else:
        notes_paragraph.alignment = WD_ALIGN_PARAGRAPH.LEFT

    if notes_paragraph.runs:
        notes_run = notes_paragraph.runs[0]
        notes_run.font.size = Pt(11)

    # Step 6: Add a footer with metadata
    doc.add_paragraph()  # Spacer
    footer = doc.add_paragraph('Generated by Sabaza Optimizer')
    footer.alignment = WD_ALIGN_PARAGRAPH.RIGHT
    if footer.runs:
        footer_run = footer.runs[0]
        footer_run.font.size = Pt(8)
        footer_run.font.italic = True
        footer_run.font.color.rgb = RGBColor(128, 128, 128)  # Gray

    # Step 7: Save to Memory (CRITICAL STEP)
    # We use BytesIO to save the file in RAM instead of on the hard drive
    buffer = BytesIO()
    doc.save(buffer)
    buffer.seek(0)  # Rewind the buffer to the beginning so it can be read

    return buffer